version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATADBASE: cloud_computing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    networks:
      - cloud-computing

  www:
    depends_on:
      - db
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - "./:/var/www/html" 
    networks:
      - cloud-computing

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    port:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - cloud-computing

networks:
  cloud-computing:
    driver: bridge

